# Generated by Django 4.2.6 on 2023-10-27 19:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birth_year', models.DateField()),
                ('club', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('STRIKER', 'STRIKER'), ('GOALKEEPER', 'GOALKEEPER'), ('DEFENDER', 'DEFENDER')], max_length=15, null=True)),
            ],
            options={
                'ordering': ['club'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalPlayer',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('birth_year', models.DateField()),
                ('club', models.CharField(max_length=50)),
                ('role', models.CharField(blank=True, choices=[('STRIKER', 'STRIKER'), ('GOALKEEPER', 'GOALKEEPER'), ('DEFENDER', 'DEFENDER')], max_length=15, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical player',
                'verbose_name_plural': 'historical players',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
