# Generated by Django 4.2.6 on 2023-10-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalpost',
            name='category',
            field=models.CharField(choices=[('PHYSICAL_CARE', 'PHYSICAL_CARE'), ('MENTAL_HEALTH', 'MENTAL_HEALTH'), ('PLAYER_VOICE', 'PLAYER_VOICE'), ('PHYSICAL_PERFORMANCE', 'PHYSICAL_PERFORMANCE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('PHYSICAL_CARE', 'PHYSICAL_CARE'), ('MENTAL_HEALTH', 'MENTAL_HEALTH'), ('PLAYER_VOICE', 'PLAYER_VOICE'), ('PHYSICAL_PERFORMANCE', 'PHYSICAL_PERFORMANCE')], max_length=50, null=True),
        ),
    ]
