# Generated by Django 4.2.6 on 2023-10-28 01:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reflection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)])),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reflection_by_player', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='historicalselfrating',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalselfrating',
            name='player',
        ),
        migrations.RemoveField(
            model_name='mentalhealth',
            name='player',
        ),
        migrations.RemoveField(
            model_name='selfrating',
            name='player',
        ),
        migrations.DeleteModel(
            name='HistoricalMentalHealth',
        ),
        migrations.DeleteModel(
            name='HistoricalSelfRating',
        ),
        migrations.DeleteModel(
            name='MentalHealth',
        ),
        migrations.DeleteModel(
            name='SelfRating',
        ),
    ]
