# Generated by Django 4.2.6 on 2023-10-28 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reflection', '0003_alter_reflection_options_reflection_comment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='description',
        ),
        migrations.AddField(
            model_name='journal',
            name='entry',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='feelings',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='get_up',
            field=models.TextField(blank=True, null=True),
        ),
    ]
